# Generated by Django 3.1.2 on 2020-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=128, verbose_name='제목')),
                ('email', models.CharField(max_length=128, verbose_name='이메일')),
                ('content', models.CharField(max_length=128, verbose_name='내용')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact_table',
            },
        ),
    ]
