# Generated by Django 3.1.2 on 2020-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
