# Generated by Django 3.1.2 on 2020-11-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201112_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='이메일'),
        ),
    ]
